/* Generated by app/tools/bundle-styles.js — do not edit.
 * Source: design-system/tokens/tokens.css, design-system/css/base.css, design-system/css/components.css, design-system/css/web.css
 * Re-run after changing any of them. */

export const STYLESHEET = `/* ===== tokens/tokens.css ===== */
/* ==========================================================================
   Corporate Deck Design System — Design Tokens
   --------------------------------------------------------------------------
   Single source of truth for colour, type, space, radius, shadow and motion.
   Import this first; every other stylesheet in the system depends on it.

   Re-theming:  add a theme class to <html> or any container.
                <html class="theme-electric">  ->  whole document re-themes
                <section class="theme-teal">   ->  scoped re-theme
   ========================================================================== */

:root {
  /* --- Accent ramp (default: amber) ------------------------------------ */
  --accent-50:  #FFF8E6;
  --accent-100: #FFEDBF;
  --accent-300: #FFD24D;
  --accent-500: #F5B21A;
  --accent-600: #9B6B00;
  --accent-700: #6D4800;

  /* Text colour that stays legible on top of --accent-500 */
  --accent-on: #14181F;

  /* Text colour for the darker accent fill (--accent-600), used by the primary
     button's hover state. Every theme's --accent-600 is chosen to clear 4.5:1
     against white — that is what makes it safe as link and eyebrow text on the
     page ground — so white is the one value that works on it in all nine. */
  --accent-on-600: #FFFFFF;

  /* --- Ink (dark anchor) ---------------------------------------------- */
  --ink-900: #14181F;
  --ink-800: #1B2333;
  --ink-700: #233049;
  --ink-600: #3A4761;
  --ink-500: #5C6880;
  --ink-400: #8993A6;
  --ink-300: #B4BCC9;
  --ink-200: #D8DDE5;
  --ink-100: #ECEFF3;

  /* --- Surfaces -------------------------------------------------------- */
  --surface-page:    #FFFFFF;
  --surface-muted:   #F7F8FA;
  --surface-cream:   #FAF6EC;
  --surface-sunken:  #EFF1F5;
  --surface-inverse: #14181F;

  /* --- Foreground roles ------------------------------------------------ */
  --fg-strong: var(--ink-900);
  --fg-body:   var(--ink-600);
  --fg-muted:  var(--ink-400);
  --fg-on-dark:        #FFFFFF;
  --fg-on-dark-muted:  rgba(255, 255, 255, 0.72);

  /* --- Semantic -------------------------------------------------------- */
  --positive: #17A673;
  --warning:  #F5B21A;
  --negative: #E04A3F;
  --info:     #2B50EE;

  /* --- Chart series ---------------------------------------------------- */
  --chart-1: var(--accent-500);
  --chart-2: var(--ink-800);
  --chart-3: var(--accent-300);
  --chart-4: var(--ink-400);
  --chart-5: var(--accent-100);
  --chart-6: var(--ink-200);
  --chart-grid: var(--ink-100);
  --chart-axis: var(--ink-400);

  /* --- Typography ------------------------------------------------------ */
  --font-display: 'Poppins', 'Montserrat', 'Segoe UI', system-ui, -apple-system, 'Helvetica Neue', Arial, sans-serif;
  --font-body:    'Inter', 'Poppins', 'Segoe UI', system-ui, -apple-system, 'Helvetica Neue', Arial, sans-serif;
  --font-mono:    'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace;

  --fw-regular:  400;
  --fw-medium:   500;
  --fw-semibold: 600;
  --fw-bold:     700;
  --fw-black:    800;

  --fs-display: 4.5rem;
  --fs-h1:      3rem;
  --fs-h2:      2.25rem;
  --fs-h3:      1.5rem;
  --fs-h4:      1.125rem;
  --fs-body:    1rem;
  --fs-small:   0.875rem;
  --fs-caption: 0.75rem;
  --fs-eyebrow: 0.75rem;
  --fs-numeral: 5rem;

  --lh-tight:  1.06;
  --lh-snug:   1.2;
  --lh-normal: 1.45;
  --lh-loose:  1.65;

  --tracking-display: -0.03em;
  --tracking-tight:   -0.02em;
  --tracking-normal:  0;
  --tracking-eyebrow: 0.18em;

  /* --- Space (4px grid) ------------------------------------------------ */
  --space-1:  0.25rem;
  --space-2:  0.5rem;
  --space-3:  0.75rem;
  --space-4:  1rem;
  --space-5:  1.5rem;
  --space-6:  2rem;
  --space-7:  2.5rem;
  --space-8:  3rem;
  --space-9:  4rem;
  --space-10: 5rem;
  --space-11: 6rem;
  --space-12: 8rem;

  /* --- Radius ---------------------------------------------------------- */
  --radius-sm:   6px;
  --radius-md:   12px;
  --radius-lg:   20px;
  --radius-xl:   32px;
  --radius-2xl:  48px;
  --radius-pill: 999px;
  --radius-blob: 42% 58% 63% 37% / 41% 44% 56% 59%;

  /* --- Shadow ---------------------------------------------------------- */
  --shadow-sm:    0 1px 2px rgba(20, 24, 31, 0.05);
  --shadow-md:    0 4px 16px rgba(20, 24, 31, 0.07);
  --shadow-lg:    0 12px 32px rgba(20, 24, 31, 0.09);
  --shadow-xl:    0 24px 64px rgba(20, 24, 31, 0.12);
  --shadow-slide: 0 18px 48px rgba(20, 24, 31, 0.14);

  /* --- Motion ---------------------------------------------------------- */
  --duration-fast: 140ms;
  --duration-base: 220ms;
  --duration-slow: 380ms;
  --ease-standard: cubic-bezier(0.2, 0, 0.2, 1);
  --ease-enter:    cubic-bezier(0, 0, 0.2, 1);
  --ease-exit:     cubic-bezier(0.4, 0, 1, 1);

  /* --- Gradient & glow --------------------------------------------------
     Decks stay flat; the web-landing family uses these for hero surfaces and
     the soft orbs behind content. Never as a brand colour — see the brief. */
  --gradient-hero:  linear-gradient(135deg, var(--accent-600) 0%, var(--accent-500) 55%, var(--accent-300) 100%);
  --gradient-sheen: linear-gradient(135deg, var(--accent-50) 0%, var(--surface-page) 60%);
  --gradient-text:  linear-gradient(90deg, var(--accent-500), var(--accent-300));
  --glow-accent:    radial-gradient(circle, color-mix(in srgb, var(--accent-500) 38%, transparent) 0%, transparent 70%);

  /* --- Layout ---------------------------------------------------------- */
  --container-max: 1200px;
  --section-py:    6rem;
  --slide-safe:    6.5%;
}

/* ==========================================================================
   Accent themes — swap the ramp, everything downstream follows
   ========================================================================== */

.theme-amber {
  --accent-50: #FFF8E6; --accent-100: #FFEDBF; --accent-300: #FFD24D;
  --accent-500: #F5B21A; --accent-600: #9B6B00; --accent-700: #6D4800;
  --accent-on: #14181F;
}

.theme-electric {
  --accent-50: #EDF1FF; --accent-100: #D6E0FF; --accent-300: #8DA5FF;
  --accent-500: #2B50EE; --accent-600: #1D3ACC; --accent-700: #152B99;
  --accent-on: #FFFFFF;
}

.theme-navy {
  --accent-50: #EEF2F9; --accent-100: #D5DEEE; --accent-300: #8095C4;
  --accent-500: #2B4A8B; --accent-600: #1F3768; --accent-700: #152547;
  --accent-on: #FFFFFF;
}

.theme-teal {
  --accent-50: #E6F8FA; --accent-100: #C0EEF3; --accent-300: #63D6E2;
  --accent-500: #22BCCE; --accent-600: #14818D; --accent-700: #11707B;
  --accent-on: #14181F;
}

.theme-green {
  --accent-50: #E7F7EF; --accent-100: #C2EBD8; --accent-300: #63CFA1;
  --accent-500: #17A673; --accent-600: #11855C; --accent-700: #0B6244;
  --accent-on: #14181F;
}

.theme-coral {
  --accent-50: #FDEEEA; --accent-100: #FAD5CB; --accent-300: #F29B80;
  --accent-500: #E85D33; --accent-600: #C64720; --accent-700: #993518;
  --accent-on: #14181F;
}

/* Added from the favourites set — the web-landing family. Violet is the
   signature there; lime is the cream-ground outlier. */

.theme-violet {
  --accent-50: #F3EEFF; --accent-100: #E2D6FF; --accent-300: #A98BFF;
  --accent-500: #7C4DFF; --accent-600: #6534E0; --accent-700: #4B24A8;
  --accent-on: #FFFFFF;
}

.theme-indigo {
  --accent-50: #EDF0FF; --accent-100: #D8DFFF; --accent-300: #93A5FF;
  --accent-500: #4059F0; --accent-600: #2E42CC; --accent-700: #1F2E96;
  --accent-on: #FFFFFF;
}

.theme-lime {
  --accent-50: #F7FBE8; --accent-100: #EAF5C2; --accent-300: #D8EC7E;
  --accent-500: #C3DE4A; --accent-600: #6A7C1D; --accent-700: #4C5A11;
  --accent-on: #14181F;
}

/* ==========================================================================
   Dark surface context
   Any block that sits on ink flips its foreground roles here, so components
   need no dark-specific variants of their own.
   ========================================================================== */

.on-dark {
  --fg-strong: #FFFFFF;
  --fg-body:   rgba(255, 255, 255, 0.78);
  --fg-muted:  rgba(255, 255, 255, 0.55);
  --surface-page:  var(--ink-900);
  --surface-muted: var(--ink-800);
  --chart-grid: rgba(255, 255, 255, 0.12);
  --chart-axis: rgba(255, 255, 255, 0.45);
  color: var(--fg-body);
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-fast: 0ms;
    --duration-base: 0ms;
    --duration-slow: 0ms;
  }
}


/* ===== css/base.css ===== */
/* ==========================================================================
   Corporate Deck Design System — Base
   Reset, document defaults, and the typographic primitives.
   Requires: tokens.css
   ========================================================================== */

*, *::before, *::after { box-sizing: border-box; }

html {
  -webkit-text-size-adjust: 100%;
  text-size-adjust: 100%;
}

body {
  margin: 0;
  background: var(--surface-page);
  color: var(--fg-body);
  font-family: var(--font-body);
  font-size: var(--fs-body);
  line-height: var(--lh-loose);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

img, svg, video, canvas { display: block; max-width: 100%; height: auto; }

h1, h2, h3, h4, h5, h6, p, figure, blockquote, dl, dd { margin: 0; }
ul, ol { margin: 0; padding: 0; }

a { color: var(--accent-600); text-decoration-thickness: 1px; text-underline-offset: 2px; }
a:hover { color: var(--accent-700); }

:focus-visible {
  outline: 3px solid var(--accent-500);
  outline-offset: 2px;
  border-radius: var(--radius-sm);
}

/* --------------------------------------------------------------------------
   Type primitives
   The house voice: heavy, tight display type over roomy, quiet body copy.
   -------------------------------------------------------------------------- */

.display,
.h1, .h2, .h3, .h4 {
  font-family: var(--font-display);
  color: var(--fg-strong);
  text-wrap: balance;
}

.display {
  font-size: clamp(2.75rem, 6vw, var(--fs-display));
  font-weight: var(--fw-black);
  line-height: 1.02;
  letter-spacing: var(--tracking-display);
}

.h1 {
  font-size: clamp(2.25rem, 4.5vw, var(--fs-h1));
  font-weight: var(--fw-black);
  line-height: var(--lh-tight);
  letter-spacing: -0.025em;
}

.h2 {
  font-size: clamp(1.75rem, 3.2vw, var(--fs-h2));
  font-weight: var(--fw-bold);
  line-height: 1.12;
  letter-spacing: var(--tracking-tight);
}

.h3 {
  font-size: var(--fs-h3);
  font-weight: var(--fw-bold);
  line-height: var(--lh-snug);
  letter-spacing: -0.01em;
}

.h4 {
  font-size: var(--fs-h4);
  font-weight: var(--fw-semibold);
  line-height: 1.3;
}

.body-lg { font-size: 1.125rem; line-height: var(--lh-loose); }
.body    { font-size: var(--fs-body); line-height: var(--lh-loose); }
.small   { font-size: var(--fs-small); line-height: 1.6; }
.caption { font-size: var(--fs-caption); line-height: 1.5; color: var(--fg-muted); font-weight: var(--fw-medium); }

/* The small tracked-out label that sits above nearly every headline.
   This is the single most recognisable tic of the system — use it often. */
.eyebrow {
  display: inline-block;
  font-family: var(--font-display);
  font-size: var(--fs-eyebrow);
  font-weight: var(--fw-semibold);
  letter-spacing: var(--tracking-eyebrow);
  text-transform: uppercase;
  color: var(--accent-600);
  line-height: var(--lh-snug);
}

.eyebrow--muted { color: var(--fg-muted); }

/* Two-tone headline. Wrap the emphasised word: "Doing Everything <em>Right</em>" */
.h1 em, .h2 em, .display em {
  font-style: normal;
  color: var(--accent-600);
}

/* The light/heavy headline pair seen on most cover slides:
   a thin first line, a black second line. */
.headline-pair { display: block; }
.headline-pair__light { display: block; font-weight: var(--fw-regular); }
.headline-pair__heavy { display: block; font-weight: var(--fw-black); }

/* Oversized ghost numeral used behind section dividers and stat blocks. */
.numeral {
  font-family: var(--font-display);
  font-size: var(--fs-numeral);
  font-weight: var(--fw-black);
  line-height: 0.9;
  letter-spacing: -0.04em;
  color: var(--fg-strong);
  font-variant-numeric: tabular-nums;
}

.numeral--ghost { color: var(--ink-100); }
.numeral--accent { color: var(--accent-500); }

/* The short accent rule that separates an eyebrow or headline from its body. */
.rule {
  width: 56px;
  height: 4px;
  border: 0;
  background: var(--accent-500);
  border-radius: var(--radius-pill);
  margin: 0;
}

.rule--center { margin-inline: auto; }
.rule--long { width: 100%; height: 1px; background: var(--ink-200); border-radius: 0; }

/* --------------------------------------------------------------------------
   Utilities
   -------------------------------------------------------------------------- */

.stack > * + * { margin-top: var(--flow, var(--space-4)); }
.stack-2 { --flow: var(--space-2); }
.stack-3 { --flow: var(--space-3); }
.stack-5 { --flow: var(--space-5); }
.stack-6 { --flow: var(--space-6); }

.container {
  width: 100%;
  max-width: var(--container-max);
  margin-inline: auto;
  padding-inline: var(--space-5);
}

.section { padding-block: var(--section-py); }
.section--muted  { background: var(--surface-muted); }
.section--cream  { background: var(--surface-cream); }
.section--accent { background: var(--accent-500); color: var(--accent-on); }
.section--dark   { background: var(--ink-900); }

.text-center { text-align: center; }
.text-accent { color: var(--accent-600); }
.text-strong { color: var(--fg-strong); }
.text-muted  { color: var(--fg-muted); }

.measure    { max-width: 62ch; }
.measure-sm { max-width: 46ch; }

.visually-hidden {
  position: absolute;
  width: 1px; height: 1px;
  padding: 0; margin: -1px;
  overflow: hidden;
  clip-path: inset(50%);
  white-space: nowrap;
}


/* ===== css/components.css ===== */
/* ==========================================================================
   Corporate Deck Design System — Components
   The recurring furniture: cards, stats, steps, timelines, buttons, tables,
   photo treatments and the decorative geometry.
   Requires: tokens.css, base.css
   ========================================================================== */

/* --------------------------------------------------------------------------
   Grid
   -------------------------------------------------------------------------- */

.grid {
  display: grid;
  gap: var(--space-5);
  grid-template-columns: repeat(var(--cols, 3), minmax(0, 1fr));
}
.grid--2 { --cols: 2; }
.grid--3 { --cols: 3; }
.grid--4 { --cols: 4; }
.grid--gap-lg { gap: var(--space-7); }

/* Asymmetric split: the workhorse layout for "headline left, content right". */
.split {
  display: grid;
  gap: var(--space-8);
  grid-template-columns: minmax(0, var(--split, 5fr)) minmax(0, 7fr);
  align-items: center;
}
.split--even    { --split: 6fr; }
.split--wide-l  { --split: 7fr; }

@media (max-width: 900px) {
  .grid { grid-template-columns: 1fr; }
  .grid--2, .grid--3, .grid--4 { grid-template-columns: 1fr; }
  .split { grid-template-columns: 1fr; gap: var(--space-6); }
}

/* --------------------------------------------------------------------------
   Card — the base container for almost every content block
   -------------------------------------------------------------------------- */

.card {
  background: var(--surface-page);
  border: 1px solid var(--ink-100);
  border-radius: var(--radius-lg);
  padding: var(--space-6);
  box-shadow: var(--shadow-sm);
  transition: box-shadow var(--duration-base) var(--ease-standard),
              transform var(--duration-base) var(--ease-standard);
}

.card--raised { box-shadow: var(--shadow-md); border-color: transparent; }
.card--flat   { box-shadow: none; background: var(--surface-muted); border-color: transparent; }
.card--accent { background: var(--accent-500); border-color: transparent; color: var(--accent-on); }
.card--dark   { background: var(--ink-900); border-color: transparent; }
.card--interactive:hover { box-shadow: var(--shadow-lg); transform: translateY(-3px); }

.card--accent .card__title,
.card--accent .h3 { color: var(--accent-on); }
.card--accent .card__body { color: color-mix(in srgb, var(--accent-on) 78%, transparent); }

/* Left accent bar — used to mark the "featured" item in a row of three. */
.card--barred {
  border-left: 4px solid var(--accent-500);
  border-radius: var(--radius-sm) var(--radius-lg) var(--radius-lg) var(--radius-sm);
}

/* Top accent bar — the alternative emphasis treatment. */
.card--capped { border-top: 4px solid var(--accent-500); }

.card__title { font-family: var(--font-display); font-size: var(--fs-h4); font-weight: var(--fw-bold); color: var(--fg-strong); }
.card__body  { font-size: var(--fs-small); color: var(--fg-body); margin-top: var(--space-2); }

/* --------------------------------------------------------------------------
   Icon chip — icon in a rounded square or circle, always accent-filled
   -------------------------------------------------------------------------- */

.icon-chip {
  display: inline-grid;
  place-items: center;
  width: 52px;
  height: 52px;
  border-radius: var(--radius-md);
  background: var(--accent-500);
  color: var(--accent-on);
  flex: none;
}

.icon-chip--round { border-radius: var(--radius-pill); }
.icon-chip--soft  { background: var(--accent-50); color: var(--accent-700); }
.icon-chip--dark  { background: var(--ink-900); color: #fff; }
.icon-chip--outline {
  background: transparent;
  border: 2px solid var(--accent-500);
  color: var(--accent-600);
}
.icon-chip--sm { width: 38px; height: 38px; border-radius: var(--radius-sm); }
.icon-chip--lg { width: 72px; height: 72px; border-radius: var(--radius-lg); }

.icon-chip svg { width: 45%; height: 45%; }

/* Feature row: chip left, copy right. The most-used content atom in the set. */
.feature {
  display: flex;
  gap: var(--space-4);
  align-items: flex-start;
}
.feature__title { font-family: var(--font-display); font-weight: var(--fw-semibold); color: var(--fg-strong); }
.feature__body  { font-size: var(--fs-small); color: var(--fg-body); margin-top: var(--space-1); }

/* --------------------------------------------------------------------------
   Stat — big number over a quiet label
   -------------------------------------------------------------------------- */

.stat { display: flex; flex-direction: column; gap: var(--space-1); }

.stat__value {
  font-family: var(--font-display);
  font-size: clamp(2.25rem, 4vw, 3.25rem);
  font-weight: var(--fw-black);
  line-height: 1;
  letter-spacing: -0.035em;
  color: var(--accent-600);
  font-variant-numeric: tabular-nums;
}

.stat__label {
  font-size: var(--fs-caption);
  font-weight: var(--fw-semibold);
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--fg-muted);
}

.stat__note { font-size: var(--fs-small); color: var(--fg-body); }
.stat--ink .stat__value { color: var(--fg-strong); }

.stat-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: var(--space-6);
}

/* Divided stat strip — hairline rules between each figure. */
.stat-row--divided > .stat + .stat {
  border-left: 1px solid var(--ink-200);
  padding-left: var(--space-6);
}
.on-dark .stat-row--divided > .stat + .stat { border-left-color: rgba(255,255,255,0.18); }
.on-dark .stat__value { color: var(--accent-300); }

@media (max-width: 700px) {
  .stat-row--divided > .stat + .stat { border-left: 0; padding-left: 0; }
}

/* --------------------------------------------------------------------------
   Numbered steps — "01 / 02 / 03" process rows
   -------------------------------------------------------------------------- */

.steps { display: grid; gap: var(--space-6); grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); counter-reset: step; }

.step { position: relative; padding-top: var(--space-6); }

.step::before {
  counter-increment: step;
  content: "0" counter(step);
  position: absolute;
  top: 0;
  left: 0;
  font-family: var(--font-display);
  font-size: 2.5rem;
  font-weight: var(--fw-black);
  line-height: 1;
  letter-spacing: -0.04em;
  color: var(--accent-100);
}

.step__title { font-family: var(--font-display); font-weight: var(--fw-bold); color: var(--fg-strong); position: relative; }
.step__body  { font-size: var(--fs-small); margin-top: var(--space-2); }

/* Badge variant — the number sits in a filled chip instead of ghosting behind. */
.step-badge {
  display: inline-grid;
  place-items: center;
  min-width: 44px;
  height: 44px;
  padding-inline: var(--space-3);
  border-radius: var(--radius-pill);
  background: var(--accent-500);
  color: var(--accent-on);
  font-family: var(--font-display);
  font-weight: var(--fw-bold);
  font-variant-numeric: tabular-nums;
}

/* --------------------------------------------------------------------------
   Timeline — horizontal milestone track
   -------------------------------------------------------------------------- */

.timeline {
  display: grid;
  grid-auto-flow: column;
  grid-auto-columns: 1fr;
  gap: var(--space-5);
  position: relative;
  padding-top: var(--space-7);
}

.timeline::before {
  content: "";
  position: absolute;
  top: 10px;
  left: 0;
  right: 0;
  height: 2px;
  background: var(--ink-200);
}

.timeline__item { position: relative; }

.timeline__item::before {
  content: "";
  position: absolute;
  top: calc(var(--space-7) * -1 + 4px);
  left: 0;
  width: 14px;
  height: 14px;
  border-radius: var(--radius-pill);
  background: var(--accent-500);
  box-shadow: 0 0 0 4px var(--surface-page);
}

.timeline__date {
  font-family: var(--font-display);
  font-weight: var(--fw-bold);
  color: var(--accent-600);
  font-variant-numeric: tabular-nums;
}
.timeline__body { font-size: var(--fs-small); margin-top: var(--space-1); }

@media (max-width: 800px) {
  .timeline { grid-auto-flow: row; padding-top: 0; padding-left: var(--space-6); }
  .timeline::before { top: 0; bottom: 0; left: 6px; right: auto; width: 2px; height: auto; }
  .timeline__item::before { top: 4px; left: calc(var(--space-6) * -1); }
}

/* --------------------------------------------------------------------------
   Buttons
   -------------------------------------------------------------------------- */

.btn {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  padding: 0.85rem 1.75rem;
  border: 2px solid transparent;
  border-radius: var(--radius-pill);
  font-family: var(--font-display);
  font-size: var(--fs-small);
  font-weight: var(--fw-semibold);
  letter-spacing: 0.01em;
  text-decoration: none;
  cursor: pointer;
  transition: background var(--duration-base) var(--ease-standard),
              color var(--duration-base) var(--ease-standard),
              transform var(--duration-fast) var(--ease-standard);
}

.btn:hover { transform: translateY(-1px); }
.btn:active { transform: translateY(0); }

.btn--primary { background: var(--accent-500); color: var(--accent-on); }
.btn--primary:hover { background: var(--accent-600); color: var(--accent-on-600); }

.btn--ink { background: var(--ink-900); color: #fff; }
.btn--ink:hover { background: var(--ink-800); color: #fff; }

.btn--outline { border-color: var(--accent-500); color: var(--accent-600); background: transparent; }
.btn--outline:hover { background: var(--accent-500); color: var(--accent-on); }

.btn--ghost { color: var(--fg-strong); background: transparent; padding-inline: var(--space-2); }
.btn--ghost:hover { color: var(--accent-600); }

.btn--square { border-radius: var(--radius-md); }
.btn--lg { padding: 1.05rem 2.25rem; font-size: var(--fs-body); }

/* Pill tag / chip label */
.tag {
  display: inline-block;
  padding: 0.35rem 0.85rem;
  border-radius: var(--radius-pill);
  background: var(--accent-50);
  color: var(--accent-700);
  font-size: var(--fs-caption);
  font-weight: var(--fw-semibold);
  letter-spacing: 0.04em;
}
.tag--solid { background: var(--accent-500); color: var(--accent-on); }
.tag--ink   { background: var(--ink-900); color: #fff; }

/* --------------------------------------------------------------------------
   Media — photo treatments
   -------------------------------------------------------------------------- */

.media {
  border-radius: var(--radius-lg);
  overflow: hidden;
  background: var(--surface-sunken);
}
.media img { width: 100%; height: 100%; object-fit: cover; }

.media--xl     { border-radius: var(--radius-xl); }
.media--pill   { border-radius: var(--radius-pill); }
.media--blob   { border-radius: var(--radius-blob); }
.media--square { border-radius: 0; }

/* The rounded-rect-with-one-square-corner mask used on section covers. */
.media--notched { border-radius: var(--radius-xl) var(--radius-xl) var(--radius-xl) 0; }

.media--circle { border-radius: var(--radius-pill); aspect-ratio: 1; }
.media--4x3 { aspect-ratio: 4 / 3; }
.media--16x9 { aspect-ratio: 16 / 9; }
.media--3x4 { aspect-ratio: 3 / 4; }

/* Accent duotone wash — turns any stock photo into brand furniture. */
.media--wash { position: relative; }
.media--wash::after {
  content: "";
  position: absolute;
  inset: 0;
  background: var(--accent-500);
  mix-blend-mode: multiply;
  opacity: 0.55;
}

.media--dim { position: relative; }
.media--dim::after {
  content: "";
  position: absolute;
  inset: 0;
  background: linear-gradient(180deg, rgba(20,24,31,0.15) 0%, rgba(20,24,31,0.72) 100%);
}

/* Avatar */
.avatar {
  width: 96px;
  height: 96px;
  border-radius: var(--radius-pill);
  object-fit: cover;
  border: 4px solid var(--surface-page);
  box-shadow: var(--shadow-md);
}
.avatar--sm { width: 48px; height: 48px; border-width: 2px; }
.avatar--ring { border-color: var(--accent-500); }

/* --------------------------------------------------------------------------
   Decorative geometry
   The blobs, quarter-circles and offset blocks that sit behind content.
   All are aria-hidden ornaments — never put meaning in them.
   -------------------------------------------------------------------------- */

/* Ornaments sit on a negative layer so they fall behind in-flow content
   without needing a z-index on the content itself — which would otherwise
   clobber the \`position: absolute\` on slide furniture. \`.has-deco\` isolates,
   so a negative layer never escapes behind the container's own background. */
.deco { position: absolute; pointer-events: none; z-index: -1; }

.deco-circle {
  border-radius: var(--radius-pill);
  background: var(--accent-500);
}
.deco-circle--soft  { background: var(--accent-50); }
.deco-circle--ink   { background: var(--ink-100); }
.deco-circle--ring  { background: transparent; border: 2px solid var(--accent-300); }

/* Quarter-circle corner ornament. */
.deco-quarter {
  border-radius: 0 0 100% 0;
  background: var(--accent-100);
}

.deco-blob {
  border-radius: var(--radius-blob);
  background: var(--accent-100);
}

/* Dotted matrix — the small grid of dots tucked into slide corners. */
.deco-dots {
  background-image: radial-gradient(var(--accent-300) 1.5px, transparent 1.5px);
  background-size: 12px 12px;
  opacity: 0.6;
}

/* Offset block behind a card or image — the "stacked paper" look.
   The accent slab is kept *inside* the element's own box (via padding) rather
   than bled outside it, so the effect survives any ancestor that clips
   overflow — which \`.has-deco\` and \`.slide\` both do. */
.offset-block {
  position: relative;
  isolation: isolate;
  padding: 0 var(--offset-shift, var(--space-5)) var(--offset-shift, var(--space-5)) 0;
}
.offset-block::before {
  content: "";
  position: absolute;
  inset: var(--offset-shift, var(--space-5)) 0 0 var(--offset-shift, var(--space-5));
  background: var(--accent-500);
  border-radius: var(--radius-lg);
  z-index: -1;
}

/* Shift the slab to the other side. */
.offset-block--left {
  padding: 0 0 var(--offset-shift, var(--space-5)) var(--offset-shift, var(--space-5));
}
.offset-block--left::before {
  inset: var(--offset-shift, var(--space-5)) var(--offset-shift, var(--space-5)) 0 0;
}

.slide .offset-block { --offset-shift: 2.4cqw; }

/* Anything that hosts .deco children needs this. */
.has-deco { position: relative; overflow: hidden; isolation: isolate; }

/* --------------------------------------------------------------------------
   Progress / meters
   -------------------------------------------------------------------------- */

.meter {
  height: 8px;
  border-radius: var(--radius-pill);
  background: var(--ink-100);
  overflow: hidden;
}
.meter__fill {
  height: 100%;
  border-radius: inherit;
  background: var(--accent-500);
}
.meter--thick { height: 14px; }

.meter-row { display: grid; gap: var(--space-2); }
.meter-row__head {
  display: flex;
  justify-content: space-between;
  font-size: var(--fs-small);
  font-weight: var(--fw-semibold);
  color: var(--fg-strong);
}

/* --------------------------------------------------------------------------
   Table
   -------------------------------------------------------------------------- */

.table-wrap { overflow-x: auto; }

.table {
  width: 100%;
  border-collapse: collapse;
  font-size: var(--fs-small);
  min-width: 520px;
}

.table th {
  text-align: left;
  font-family: var(--font-display);
  font-size: var(--fs-caption);
  font-weight: var(--fw-semibold);
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--fg-muted);
  padding: var(--space-3) var(--space-4);
  border-bottom: 2px solid var(--ink-200);
  white-space: nowrap;
}

.table td {
  padding: var(--space-4);
  border-bottom: 1px solid var(--ink-100);
  color: var(--fg-body);
}

.table tbody tr:hover { background: var(--surface-muted); }
.table td:first-child { font-weight: var(--fw-semibold); color: var(--fg-strong); }

/* --------------------------------------------------------------------------
   Quote / testimonial
   -------------------------------------------------------------------------- */

.quote {
  position: relative;
  padding-left: var(--space-7);
  font-family: var(--font-display);
  font-size: 1.25rem;
  font-weight: var(--fw-medium);
  line-height: 1.5;
  color: var(--fg-strong);
}

.quote::before {
  content: "\\201C";
  position: absolute;
  left: 0;
  top: -0.35em;
  font-size: 4rem;
  line-height: 1;
  color: var(--accent-300);
}

.quote__cite {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  margin-top: var(--space-5);
  font-family: var(--font-body);
  font-size: var(--fs-small);
  font-weight: var(--fw-regular);
  color: var(--fg-muted);
}
.quote__name { font-weight: var(--fw-semibold); color: var(--fg-strong); display: block; }

/* --------------------------------------------------------------------------
   SWOT — the 2x2 that appears in nearly every deck in the reference set
   -------------------------------------------------------------------------- */

.swot { display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-4); }
.swot > * { padding: var(--space-5); border-radius: var(--radius-lg); }
.swot__s { background: var(--accent-500); color: var(--accent-on); }
.swot__w { background: var(--ink-900); color: #fff; }
.swot__o { background: var(--accent-50); color: var(--ink-900); }
.swot__t { background: var(--surface-muted); color: var(--ink-900); }
.swot__label {
  font-family: var(--font-display);
  font-size: var(--fs-caption);
  font-weight: var(--fw-bold);
  letter-spacing: 0.14em;
  text-transform: uppercase;
  opacity: 0.75;
}
.swot__body { font-size: var(--fs-small); margin-top: var(--space-2); }

@media (max-width: 700px) { .swot { grid-template-columns: 1fr; } }

/* --------------------------------------------------------------------------
   Navbar (web templates)
   -------------------------------------------------------------------------- */

.navbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-6);
  padding: var(--space-4) 0;
}

.navbar__brand {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  font-family: var(--font-display);
  font-size: 1.125rem;
  font-weight: var(--fw-bold);
  letter-spacing: -0.01em;
  color: var(--fg-strong);
  text-decoration: none;
}

.navbar__links {
  display: flex;
  gap: var(--space-6);
  list-style: none;
  font-size: var(--fs-small);
  font-weight: var(--fw-medium);
}
.navbar__links a { color: var(--fg-body); text-decoration: none; }
.navbar__links a:hover { color: var(--accent-600); }

@media (max-width: 800px) { .navbar__links { display: none; } }


/* ===== css/web.css ===== */
/* ==========================================================================
   Corporate Deck Design System — Web layer
   Patterns from the favourites set (see FAVORITES.md) that the deck layer
   does not cover: gradient heroes, wave dividers, device mockups, trust bars,
   tinted feature cards, ghost step rails, pricing, FAQ, marquee, CTA bands.
   Requires: tokens.css, base.css, components.css
   ========================================================================== */

/* --------------------------------------------------------------------------
   Hero surfaces
   -------------------------------------------------------------------------- */

.hero-gradient {
  position: relative;
  background: var(--gradient-hero);
  color: #fff;
  isolation: isolate;
  overflow: hidden;
}
.hero-gradient .h1,
.hero-gradient .display,
.hero-gradient .h2 { color: #fff; }
.hero-gradient .eyebrow { color: rgba(255, 255, 255, 0.75); }

.hero-sheen { background: var(--gradient-sheen); }

/* Soft blurred orb — the glow behind hero content. Ornamental. */
.orb {
  position: absolute;
  border-radius: var(--radius-pill);
  background: var(--glow-accent);
  filter: blur(28px);
  pointer-events: none;
  z-index: -1;
}

/* Wave divider. Sits at the bottom of a coloured hero and curves into the
   next section. Give it the *next* section's background via \`color\`. */
.wave {
  display: block;
  width: 100%;
  height: clamp(40px, 6vw, 90px);
  color: var(--surface-page);
}
.wave svg { display: block; width: 100%; height: 100%; }
.wave path { fill: currentColor; }

/* --------------------------------------------------------------------------
   Badge pill above a headline — "NEW · Introducing X"
   -------------------------------------------------------------------------- */

.badge-pill {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  padding: 0.35rem 0.35rem 0.35rem 0.85rem;
  border-radius: var(--radius-pill);
  background: var(--accent-50);
  color: var(--accent-700);
  font-size: var(--fs-caption);
  font-weight: var(--fw-semibold);
}
.badge-pill__flag {
  padding: 0.2rem 0.6rem;
  border-radius: var(--radius-pill);
  background: var(--accent-500);
  color: var(--accent-on);
  font-size: 0.6875rem;
  letter-spacing: 0.06em;
  text-transform: uppercase;
}
.hero-gradient .badge-pill {
  background: rgba(255, 255, 255, 0.16);
  color: #fff;
}

/* Headline word with an accent underline rather than an accent fill. */
.underlined {
  color: var(--accent-600);
  text-decoration: underline;
  text-decoration-thickness: 0.09em;
  text-underline-offset: 0.12em;
}

/* Gradient-filled headline word. Use once per page at most. */
.gradient-text {
  background: var(--gradient-text);
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}

/* --------------------------------------------------------------------------
   Device mockup frames — the product-UI hero visual
   -------------------------------------------------------------------------- */

.device {
  position: relative;
  background: var(--ink-900);
  box-shadow: var(--shadow-xl);
  overflow: hidden;
}

.device--phone {
  border-radius: 2.25rem;
  padding: 0.55rem;
  aspect-ratio: 1179 / 2556;
  max-width: 300px;
}
.device--phone::before {              /* dynamic island */
  content: "";
  position: absolute;
  top: 1.1rem; left: 50%;
  transform: translateX(-50%);
  width: 32%; height: 1.1rem;
  border-radius: var(--radius-pill);
  background: var(--ink-900);
  z-index: 2;
}

.device--browser {
  border-radius: var(--radius-md);
  padding: 1.9rem 0.4rem 0.4rem;
}
.device--browser::before {            /* traffic lights */
  content: "";
  position: absolute;
  top: 0.72rem; left: 0.85rem;
  width: 2.6rem; height: 0.45rem;
  border-radius: var(--radius-pill);
  background:
    radial-gradient(circle 3.5px at 3.5px 50%, var(--ink-600) 100%, transparent 0) 0 0/1rem 100% no-repeat,
    radial-gradient(circle 3.5px at 3.5px 50%, var(--ink-600) 100%, transparent 0) 0.85rem 0/1rem 100% no-repeat,
    radial-gradient(circle 3.5px at 3.5px 50%, var(--ink-600) 100%, transparent 0) 1.7rem 0/1rem 100% no-repeat;
}

.device__screen {
  border-radius: inherit;
  overflow: hidden;
  background: var(--surface-page);
  height: 100%;
}
.device--browser .device__screen { border-radius: var(--radius-sm); }
.device__screen img { width: 100%; height: 100%; object-fit: cover; object-position: top; }

/* Small stat/notification card that floats over a mockup. */
.float-card {
  position: absolute;
  z-index: 3;
  background: var(--surface-page);
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-lg);
  padding: var(--space-3) var(--space-4);
  font-size: var(--fs-caption);
  color: var(--fg-body);
  max-width: 200px;
}
.float-card__value {
  font-family: var(--font-display);
  font-size: 1.125rem;
  font-weight: var(--fw-bold);
  color: var(--fg-strong);
  line-height: 1.2;
}

/* Floating label chip — the tags pinned around a portrait. */
.pin {
  position: absolute;
  z-index: 3;
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  padding: 0.45rem 0.9rem;
  border-radius: var(--radius-pill);
  background: var(--surface-page);
  box-shadow: var(--shadow-md);
  font-size: var(--fs-caption);
  font-weight: var(--fw-semibold);
  color: var(--fg-strong);
  white-space: nowrap;
}
.pin--ink { background: var(--ink-900); color: #fff; }
.pin::before {
  content: "";
  width: 7px; height: 7px;
  border-radius: var(--radius-pill);
  background: var(--accent-500);
}

/* --------------------------------------------------------------------------
   Trust bar — "Loved by innovative teams" + logo row
   -------------------------------------------------------------------------- */

.trustbar {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-8);
  flex-wrap: wrap;
}
.trustbar__label {
  font-size: var(--fs-small);
  font-weight: var(--fw-medium);
  color: var(--fg-muted);
}
.trustbar__logos {
  display: flex;
  align-items: center;
  gap: var(--space-8);
  flex-wrap: wrap;
  list-style: none;
}
.trustbar__logos li {
  font-family: var(--font-display);
  font-size: 1.125rem;
  font-weight: var(--fw-bold);
  color: var(--ink-400);
  letter-spacing: -0.01em;
}

/* --------------------------------------------------------------------------
   Tinted feature cards — each card a different soft tint
   -------------------------------------------------------------------------- */

.tint-grid { display: grid; gap: var(--space-4); grid-template-columns: repeat(var(--cols, 4), minmax(0, 1fr)); }

.tint-card {
  padding: var(--space-5);
  border-radius: var(--radius-lg);
  background: var(--tint, var(--accent-50));
}
.tint-card__title { font-family: var(--font-display); font-weight: var(--fw-bold); color: var(--fg-strong); margin-top: var(--space-3); }
.tint-card__body  { font-size: var(--fs-small); color: var(--fg-body); margin-top: var(--space-2); }

/* Four house tints. They are *neutral supports*, not second accents — each is
   desaturated far enough that the accent still owns every emphasis on the page. */
.tint-1 { --tint: var(--accent-50); }
.tint-2 { --tint: #FFF1E8; }
.tint-3 { --tint: #E9F7EF; }
.tint-4 { --tint: #EAF2FF; }

@media (max-width: 900px) { .tint-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }
@media (max-width: 560px) { .tint-grid { grid-template-columns: 1fr; } }

/* --------------------------------------------------------------------------
   Step rail — oversized ghost numerals down a dotted centre line
   Alternating sides, copy one side / visual the other.
   -------------------------------------------------------------------------- */

.rail { position: relative; display: grid; gap: var(--space-10); }

.rail::before {                      /* the dotted spine */
  content: "";
  position: absolute;
  top: 0; bottom: 0; left: 50%;
  border-left: 2px dotted var(--ink-200);
}

.rail__row {
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  gap: var(--space-6);
  align-items: center;
}

.rail__num {
  font-family: var(--font-display);
  font-size: clamp(3.5rem, 7vw, 6rem);
  font-weight: var(--fw-black);
  line-height: 1;
  letter-spacing: -0.04em;
  color: var(--ink-100);
  background: var(--surface-page);
  padding-block: var(--space-3);
  font-variant-numeric: tabular-nums;
  text-align: center;
}
.rail__num--label::before {
  content: "STEP";
  display: block;
  font-size: 0.75rem;
  font-weight: var(--fw-semibold);
  letter-spacing: 0.18em;
  color: var(--ink-300);
}

/* Every child needs an explicit order, or the numeral keeps its default 0 and
   lands in the first column — pushing the visual into the narrow centre one. */
.rail__row--flip .rail__visual { order: 1; }
.rail__row--flip .rail__num    { order: 2; }
.rail__row--flip .rail__copy   { order: 3; }

@media (max-width: 800px) {
  .rail::before { left: 18px; }
  .rail__row { grid-template-columns: auto 1fr; gap: var(--space-4); }
  .rail__row .rail__num { order: 1; font-size: 2.5rem; }
  .rail__row .rail__copy { order: 2; }
  .rail__row .rail__visual { order: 3; grid-column: 2; }
}

/* --------------------------------------------------------------------------
   Pricing
   -------------------------------------------------------------------------- */

.price-grid { display: grid; gap: var(--space-5); grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); align-items: start; }

.price-card {
  position: relative;
  padding: var(--space-6);
  border: 1px solid var(--ink-100);
  border-radius: var(--radius-lg);
  background: var(--surface-page);
}
.price-card--featured {
  border-color: var(--accent-500);
  border-width: 2px;
  box-shadow: var(--shadow-lg);
}
.price-card__flag {
  position: absolute;
  top: 0; left: 50%;
  transform: translate(-50%, -50%);
  padding: 0.3rem 0.9rem;
  border-radius: var(--radius-pill);
  background: var(--accent-500);
  color: var(--accent-on);
  font-size: var(--fs-caption);
  font-weight: var(--fw-semibold);
  white-space: nowrap;
}
.price-card__amount {
  font-family: var(--font-display);
  font-size: 2.75rem;
  font-weight: var(--fw-black);
  letter-spacing: -0.035em;
  color: var(--fg-strong);
  line-height: 1;
}
.price-card__period { font-size: var(--fs-small); color: var(--fg-muted); }

.checklist { list-style: none; display: grid; gap: var(--space-3); font-size: var(--fs-small); }
.checklist li { display: flex; gap: var(--space-3); align-items: flex-start; }
.checklist li::before {
  content: "";
  flex: none;
  width: 18px; height: 18px;
  margin-top: 2px;
  border-radius: var(--radius-pill);
  background: var(--accent-500);
  -webkit-mask: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath d='m5 13 4 4L19 7' fill='none' stroke='%23000' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E") center/12px no-repeat,
           linear-gradient(#000 0 0);
  -webkit-mask-composite: xor;
          mask: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath d='m5 13 4 4L19 7' fill='none' stroke='%23000' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E") center/12px no-repeat,
                linear-gradient(#000 0 0);
          mask-composite: exclude;
}

/* --------------------------------------------------------------------------
   FAQ accordion
   -------------------------------------------------------------------------- */

.faq { display: grid; gap: var(--space-3); }

.faq__item {
  border: 1px solid var(--ink-100);
  border-radius: var(--radius-md);
  background: var(--surface-page);
  padding: var(--space-4) var(--space-5);
}
.faq__item[open] { border-color: var(--accent-300); }

.faq__q {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: var(--space-4);
  cursor: pointer;
  list-style: none;
  font-family: var(--font-display);
  font-size: var(--fs-small);
  font-weight: var(--fw-semibold);
  color: var(--fg-strong);
}
.faq__q::-webkit-details-marker { display: none; }
.faq__q::after {
  content: "+";
  font-size: 1.25rem;
  font-weight: var(--fw-regular);
  color: var(--accent-600);
  line-height: 1;
}
.faq__item[open] .faq__q::after { content: "\\2212"; }
.faq__a { font-size: var(--fs-small); color: var(--fg-body); margin-top: var(--space-3); }

/* --------------------------------------------------------------------------
   Marquee strip — the scrolling keyword band
   -------------------------------------------------------------------------- */

.marquee {
  overflow: hidden;
  background: var(--accent-500);
  color: var(--accent-on);
  padding-block: var(--space-3);
}
.marquee__track {
  display: flex;
  gap: var(--space-6);
  width: max-content;
  animation: marquee-scroll 26s linear infinite;
  font-family: var(--font-display);
  font-size: 1.125rem;
  font-weight: var(--fw-semibold);
}
.marquee__track > span { display: flex; align-items: center; gap: var(--space-6); }
.marquee__track > span::after { content: "\\2726"; opacity: 0.6; }

@keyframes marquee-scroll { to { transform: translateX(-50%); } }
@media (prefers-reduced-motion: reduce) {
  .marquee__track { animation: none; }
}

/* --------------------------------------------------------------------------
   CTA band — full-width accent slab with copy left, action right
   -------------------------------------------------------------------------- */

.cta-band {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-6);
  flex-wrap: wrap;
  padding: var(--space-7) var(--space-8);
  border-radius: var(--radius-xl);
  background: var(--accent-500);
  color: var(--accent-on);
}
.cta-band--gradient { background: var(--gradient-hero); color: #fff; }
.cta-band .h3 { color: inherit; }

/* Newsletter input group */
.field-group {
  display: flex;
  gap: var(--space-2);
  background: var(--surface-page);
  border: 1px solid var(--ink-200);
  border-radius: var(--radius-pill);
  padding: 0.3rem 0.3rem 0.3rem 1.1rem;
  max-width: 420px;
}
.field-group input {
  flex: 1;
  min-width: 0;
  border: 0;
  background: transparent;
  font: inherit;
  font-size: var(--fs-small);
  color: var(--fg-strong);
}
.field-group input:focus { outline: none; }
.field-group:focus-within { border-color: var(--accent-500); }

/* --------------------------------------------------------------------------
   Dark page variant
   The favourites include a fully dark portfolio. \`on-dark\` flips foreground
   roles; these few overrides carry the web components across with it.
   -------------------------------------------------------------------------- */

.on-dark .card,
.on-dark .price-card,
.on-dark .faq__item,
.on-dark .float-card {
  background: var(--ink-800);
  border-color: rgba(255, 255, 255, 0.09);
}
.on-dark .tint-card { background: rgba(255, 255, 255, 0.05); }
.on-dark .rail__num { background: var(--ink-900); color: rgba(255, 255, 255, 0.12); }
.on-dark .rail::before { border-color: rgba(255, 255, 255, 0.16); }
.on-dark .trustbar__logos li { color: rgba(255, 255, 255, 0.45); }
.on-dark .badge-pill { background: rgba(255, 255, 255, 0.1); color: var(--accent-300); }
.on-dark .field-group { background: rgba(255, 255, 255, 0.06); border-color: rgba(255, 255, 255, 0.14); }
.on-dark .field-group input { color: #fff; }
.on-dark .underlined { color: var(--accent-300); }
`;
